plugins {
    id 'com.android.application'
}

android {
    namespace 'com.unclebanana.pulseone'
    compileSdk 36

    defaultConfig {
        applicationId 'com.unclebanana.pulseone'
        minSdk 26
        targetSdk 36
        versionCode 9
        versionName '0.2.8'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':core')
}
